apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    imagebuilder.ai.qingcloud.com: "imagebuilder-deployment"
  name: imagebuilder
spec:
  selector:
    matchLabels:
      app: imagebuilder
  template:
    metadata:
      labels:
        app: imagebuilder
    spec:
      serviceAccountName: imagebuilder-service-account
      containers:
        - name: imagebuilder-container
          image: jw008/imagebuild:v1.2.4
          env:
            - name: imagebuild_name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: imagebuild_namespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "controller"
          imagePullPolicy: Always
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: imagebuilder-service-account

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-and-node-reader
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "nodes" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups:
    - "batch"
    resources:
      - "jobs"
    verbs:
      - create
      - get
      - list
      - watch
      - delete
  - apiGroups: [ "imagebuilder.ai.qingcloud.com" ]
    resources:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: imagebuilder-pod-and-node-reader
subjects:
  - kind: ServiceAccount
    name: imagebuilder-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: pod-and-node-reader
  apiGroup: rbac.authorization.k8s.io